server:
  port: 8089
  contextPath: /main_main

spring:
  jpa:
    show-sql: true
    generate-ddl: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://scorpio.sofco:7654/gaji_id
    username: sofco
    password: s3234
    driverClassName: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: smtp.sofcograha.co.id
    port: 587
    username: sofco_sb@sofcograha.co.id
    password: pjiwo315
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  activemq:
    broker-url: failover:tcp://127.0.0.1:61616?keepAlive=true
      
paketgl:
  activemq:
    suffix: Qsuffix

hibernate:
  show_sql: true

file:
 upload-dir: /home/user/Project/traininggenerator/files

gaji-id-user:
gaji-id-pwd:
gaji-id-token-address: 
gaji-id-upload-address: http://gajiid.sofco:9580/gaji-id-local-info-api/local/query-data/jml-karyawan
gaji-id-token: 7f69993d418b8f87aee5e367e5e859974a623a062da832c9afebdd256bc9bad5
 
